// @/types/book.ts

export type BookCondition = 'EXCELLENT' | 'GOOD' | 'FAIR' | 'POOR' | 'DAMAGED';
export type BookStatus = 'AVAILABLE' | 'ISSUED' | 'LOST' | 'DAMAGED' | 'UNDER_REPAIR' | 'UNAVAILABLE';
export type BookType = 'REFERENCE' | 'GENERAL' | 'JOURNAL' | 'MAGAZINE' | 'THESIS' | 'REPORT' | 'TEST' | 'GIFTED' | 'OTHER';

export interface Book {
  id: string; // Generated by backend
  createdAt: string; // Generated by backend
  updatedAt: string; // Generated by backend
  registrationDate: string; // Generated by backend

  accessionNumber: string;
  isbn: string;
  title: string;
  subtitle: string | null;
  authorPrimary: string;
  authorSecondary: string | null;
  publisher: string;
  publicationPlace: string;
  publicationYear: number;
  edition: string;
  pages: string;
  language: string;
  price: number;
  billNumber: string;
  vendorName: string;
  purchaseDate: string; // Should be in 'YYYY-MM-DD' format for API
  keywords: string; // Comma-separated
  classificationNumber: string;
  locationShelf: string;
  locationRack: string;
  bookCondition: BookCondition;
  bookStatus: BookStatus;
  totalCopies: number;
  availableCopies: number;
  bookType: BookType;
  isReferenceOnly: boolean;
  notes: string;
}

// These are not used in the 'add book' component but are good to keep.
export interface Pagination {
  totalElements: number;
  totalPages: number;
  currentPage: number;
  pageSize: number;
}

export interface BookSearchResponse {
  status: string;
  data: Book[];
  timestamp: string;
  pagination: Pagination;
}
